spring.application.name=demoBookStore
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
spring.datasource.username=postgres
spring.datasource.password=123
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
